// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MathGen = require("./math.gen");

function add(prim0, prim1) {
  return MathGen.add(prim0, prim1);
}

exports.add = add;
/* ./math.gen Not a pure module */
